
--[[                                                                                  
█████▄  ▄▄ ▄▄ ▄▄  ▄▄▄  ▄▄     ▄▄▄▄    ▄▄▄  ▄▄▄▄     ▄▄▄▄  ▄▄▄▄ ▄▄▄▄  ▄▄ ▄▄▄▄ ▄▄▄▄▄▄   
██▄▄██▄ ██ ██▄██ ██▀██ ██    ███▄▄   ██▀██ ██▄█▀   ███▄▄ ██▀▀▀ ██▄█▄ ██ ██▄█▀  ██     
██   ██ ██  ▀█▀  ██▀██ ██▄▄▄ ▄▄██▀   ▀███▀ ██      ▄▄██▀ ▀████ ██ ██ ██ ██     ██  
                                                    
                                                    
█████▄ ██  ██   ██ ▄▄  ▄▄ ▄▄ ▄▄ ██████ ▄▄▄▄  ▄█████ 
██▄▄██  ▀██▀    ██ ███▄██ ▀█▄█▀   ██   ██▀██ ▀▀▀▄▄▄ 
██▄▄█▀   ██     ██ ██ ▀██ ██ ██   ██   ████▀ █████▀ 
                                                       
  ]]       
--V1
--loadstring(game:HttpGet("https://pastebin.com/raw/6my0KxYi"))()
--Addons
--esp and health esp
--loadstring(game:HttpGet("https://pastebin.com/raw/TnbnEb4K"))()
--undergorund baseplate
--loadstring(game:HttpGet("https://pastebin.com/raw/j9gsWUfc"))()
--V2
--loadstring(game:HttpGet("https://pastefy.app/Yd8JhZaW/raw"))()
-- Legit v1
--loadstring(game:HttpGet("https://pastefy.app/IKqPZ6YY/raw"))()



-- Legit Purple Version
--[[
purple version rivals
loadstring(game:HttpGet("https://pastefy.app/eSC9XTQl/raw"))()
purple vibe
loadstring(game:HttpGet("https://pastefy.app/1YMzbwlT/raw"))()
watermark
loadstring(game:HttpGet("https://pastefy.app/TYw5hIBW/raw"))()
]]

--[[
MM2 script
loadstring(game:HttpGet("https://pastefy.app/K2HVL9re/raw"))()
--watermark
loadstring(game:HttpGet("https://pastefy.app/TYw5hIBW/raw"))()

]]

